//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUISEI.MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleOperacion
    {
        public int id_detalle_operacion { get; set; }
        public int do_id_operacion { get; set; }
        public int do_id_producto { get; set; }
        public string do_motivo { get; set; }
        public Nullable<int> do_cantidad { get; set; }
    
        public virtual Operacion Operacion { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
