//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUISEI.MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operacion()
        {
            this.DetalleOperacion = new HashSet<DetalleOperacion>();
        }
    
        public int id_operacion { get; set; }
        public int o_id_usuario { get; set; }
        public string o_nombre { get; set; }
        public Nullable<System.DateTime> o_fecha { get; set; }
        public Nullable<System.TimeSpan> o_hora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOperacion> DetalleOperacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
