//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUISEI.MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int id_pedido { get; set; }
        public int pe_id_delivery { get; set; }
        public int pe_id_venta { get; set; }
        public string pe_descripcion { get; set; }
        public string pe_estado { get; set; }
        public Nullable<System.DateTime> pe_fecha_entrega { get; set; }
        public Nullable<System.TimeSpan> pe_hora_entrega { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
