//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUISEI.MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.DetalleRol = new HashSet<DetalleRol>();
            this.Operacion = new HashSet<Operacion>();
            this.Venta = new HashSet<Venta>();
        }
    
        public int id_usuario { get; set; }
        public string u_nom_usuario { get; set; }
        public string u_nombres { get; set; }
        public string u_paterno { get; set; }
        public string u_materno { get; set; }
        public Nullable<int> u_edad { get; set; }
        public string u_sexo { get; set; }
        public string u_direccion { get; set; }
        public string u_telefono { get; set; }
        public string u_dni { get; set; }
        public string u_estado { get; set; }
        public string u_clave { get; set; }
        public string u_respuesta_rec { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRol> DetalleRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operacion> Operacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
